#!/usr/bin/env ruby

# WHAT IS IT
# -----------
# This script is executed everytime code is pushed to github.
# It will not allow you to FORCE PUSH to MASTER.
#
# REQUIREMENT
# --------
# - Make sure that you are using git version 1.8.2 or higher. Do `brew upgrade git` to upgrade git.
#
# USAGE
# --------
# - Place this file under .git/hooks of your repository as pre-push with no extension.
# - Make this file executable by running chmod a+x pre-push .
# - make some changes to a file and try to do git push --force in master .
#
# Above technique works only for a project. If you want to use this pre-push hook for all projects then take following steps

class PrePushHandler

  def handle
    reject if pushing_to_master? && forced_push?
  end

  private

  def pushing_to_master?
    current_branch == 'master'
  end

  def current_branch
    result = %x{git branch}.split("\n")
    if result.empty?
      feedback "It seems your app is not a git repository."
    else
      result.select { |b| b =~ /^\*/ }.first.split(" ").last.strip
    end
  end

  def reject
    messages = ["Your attempt to FORCE PUSH to MASTER has been rejected."]
    messages << "If you still want to FORCE PUSH then you need to ignore the pre_push git hook by executing following command."
    messages << "git push master --force --no-verify"
    feedback messages
  end

  def forced_push?
    ppid = Process.ppid
    cmd = "ps -ocommand= -p #{ppid}"
    output = `#{cmd}`
    output.match(/--force|-f/)
  end

  def feedback messages
    puts "*"*40
    [messages].flatten.each do |message|
      puts message
    end
    puts "*"*40

    exit 1
  end
end

PrePushHandler.new.handle

