#!/usr/bin/env ruby

require_relative 'common.rb'

# this script 
# - gets the latest master
# - merges master to the current branch 
# - push the branch to github
#
# Usage :
# stand in a branch and execute uptd
#

def update_master
  execute_cmd 'git checkout master'
  execute_cmd 'git pull'
end

def rebase_current_branch branch_name
  execute_cmd "git checkout #{branch_name}"
  execute_cmd 'git rebase master'
  execute_cmd 'git push'
end

def update_current_branch
  execute_cmd 'git pull'
end

current_branch_name = branch_name

update_current_branch
update_master
rebase_current_branch(current_branch_name) unless current_branch_name == 'master'
