#!/usr/bin/env ruby

# This script is for running tests for Rails while doing development 
# work for ActiveRecord.
#
# Usage :
# stand in the rails/activerecord directory and execute
#
# art test/cases/relation_test.rb
#
cmd = "ruby -rdebugger -Itest #{ARGV.join(' ')}"
puts cmd
system cmd
