#! /usr/bin/env ruby

usage =  "usage: bo 5000 will open https://rails.lighthouseapp.com/projects/8994/tickets/5000"
raise usage if ARGV.length == 0

require 'rubygems'
require 'launchy'

url  = "https://rails.lighthouseapp.com/projects/8994/tickets/#{ARGV[0]}"
Launchy.open(url)
