#!/usr/bin/env ruby

require_relative 'common.rb'

# It will list all the commits that this branch has but master does not. 
# In other words it lists all the commits it is ahead of master.
#
# Usage:
#
# stand in the branch you want to compare against master and execute the command.
#

puts "This lists all commits present in this branch but not in master. In other words it lists " <<
     "all the commits this branch is ahead of master"

open_url "https://github.com/#{repo_owner}/#{repo_name}/compare/master...#{branch_name}"
