#!/usr/bin/env ruby

require_relative 'common.rb'

# finds and replaces text in all files in the directory you are standing in.

# Usage :
# find_replace
#

puts "Enter the word you are trying to find"
find = gets.chomp.strip

puts "Enter the word you are trying to replace the word '#{find}' with"
replace = gets.chomp.strip

if find.length == 0
  puts "Error: find word should not be empty"
  exit 1
end

if replace.length == 0
  puts "Error: replace word should not be empty"
  exit 1
end

pwd = Dir.pwd

execute_cmd %Q{perl -e "s/#{find}/#{replace}/g;" -pi $(find #{pwd} -type f)}

puts 'Done'
