#!/usr/bin/env ruby

# It turns an existing issue into a pull request.
#
# Usage:
# Stand in the branch for which you want to send pull request and execute git_create_pull_request .
#
ref_head = `git symbolic-ref HEAD`
issue_number = ref_head.gsub(%r[refs/heads/],'').to_i

organization = 'git config --get remote.origin.url | rev | cut -d/ -f2 | cut -d: -f1 | rev'
organization = %x(#{organization}).chop!

current_branch = ref_head.gsub(%r[refs/heads/],'').strip

cmd = "hub pull-request -i #{issue_number} -b #{organization}:master -h #{organization}:#{current_branch}"
puts cmd
`#{cmd}`
