#!/usr/bin/env ruby

# Sometimes I need empty commit to see if continuous integration is working or
# the git hooks are working or not.
#
# Usage:
# Stand in the branch for which you want to send pull request and execute git_empty_commit .
#
cmd = %Q{git commit -m 'empty commit' --allow-empty}
puts cmd
system cmd
