#!/usr/bin/env ruby

require_relative 'common.rb'

# It lists all the commits that is present in master but not in this branch. In other words
# it lists all the commits by which this branch is behind of master.
#
# Usage:
#
# stand in the branch you want to compare against master and execute git_ahead
#
puts "This lists all extra commits present in master but missing in #{branch_name}"

open_url "https://github.com/#{repo_owner}/#{repo_name}/compare/#{branch_name}...master"
