#!/usr/bin/env ruby
require 'rubygems'
require 'open3'

# Manually deleting local branches can be time consuming. This script
# can help.
#
# Note: This only deletes local branch. It does NOT delete remote branch.
#
# Usage :
# stand in the project directory and execute git_clearn_branches
#
# You will be prompted for a confirmation like this
# Do you want to delete branch   154-roles ?
#

Dir.chdir(Dir.pwd) do

  cmd = 'git branch'
  Open3.popen3(cmd) do |stdin, stdout, stderr, wait_thr|
    while branch = stdout.gets
      branch = branch.chomp
      next if branch =~ /master/
      puts "Do you want to delete branch #{branch} ?"
      a = gets.chomp
      if %w(y yes).include? a.downcase
        cmd = "git branch -D #{branch}"
        system cmd
        puts ""
      end
    end
  end

end
