#!/usr/bin/env ruby

require_relative 'common.rb'

# It will list all the commits this branch has but master does not. In other words it lists
# all the commits it is ahead of master.
#
# Usage:
#
# stand in the branch you want to compare against master and execute git_ahead
#

puts "This lists all extra commits present in this branch"

open_url "https://github.com/#{repo_owner}/#{repo_name}/compare/master...#{branch_name}"
