#!/usr/bin/env ruby

require 'rubygems'
require 'launchy'

# Usage:
# stand in the branch you want to compare against master and execute git_compare

string = `git remote -v | grep fetch`
regex = /.*:(.*)\/.*/
match_data = string.match(regex)
repo_name = match_data.to_a.last

project_name = `git rev-parse --show-toplevel`.split('/').last.strip

ref_head = `git symbolic-ref HEAD`
branch_name = ref_head.gsub(%r[refs/heads/],'').strip

last_unit = "master...#{branch_name}"
uri = "https://github.com/#{repo_name}/#{project_name}/compare/#{last_unit}"
puts uri
puts "This lists all extra commits present in #{branch_name}"
Launchy.open( uri )
