#!/usr/bin/env ruby

require_relative 'common.rb'

# Usage :
#
# git_download_pr <pull-request-number>
# 
# If the pull request url is https://github.com/rails/rails/pull/10798 then execute
# git_download_pr 10798
#

pr_number = ARGV.first

if pr_number.nil?
  abort "Usage: pulldown <pr-number>"
end

execute_cmd "hub checkout https://github.com/bigbinary/agent-bright/pull/#{pr_number}"
