#!/usr/bin/env ruby

require_relative 'common.rb'

# Usage :
# gitcmwa
#
# a stands for all.
#
# It would 
# - add all the changed items. 
# - will commit the changes with message WIP. 
# - will push the commit.
#
commands = []
commands << "git add -A"
commands << "git commit -m 'WIP'"
commands << "gp"

commands.each do |cmd|
  execute_cmd cmd
end
