#!/usr/bin/env ruby

# Usage :
# gitcmwa
#
# It would add all the changed items. 
# Will commit the changes with message WIP. 
# Will push the commit.
#
commands = []
commands << "git add -A"
commands << "git commit -m 'WIP'"
commands << "gp"

commands.each do |cmd|
  puts cmd
  system cmd
end
