#!/usr/bin/env ruby

require_relative 'common.rb'

# Creates missing directories and then touches the file. Best
# used inside vim.
#
# Usage :
# mktouch /Users/nsingh/dev/app/models/user.rb

require 'pathname'

pathname = Pathname.new ARGV.join('')
dirname = pathname.dirname
execute_cmd "mkdir -p #{dirname}"
execute_cmd "touch #{pathname}"
