#!/usr/bin/env ruby -w 

puts "first do rvm18"

if ARGV.nil?
  puts 'provide bug number'
  exit
end

cmd = "rm -rf rails3_#{ARGV}"
system(cmd)

cmd = "rails rails3_#{ARGV}"
puts cmd
system(cmd)


gem_info = %{
source 'http://rubygems.org'

#gem 'rails', '3.0.0.beta3'
gem 'rails', :git => 'git://github.com/rails/rails.git'
gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'ruby-debug'
}

fj = File.join(File.dirname(__FILE__), "rails3_#{ARGV}", 'Gemfile')
puts fj.inspect
f = File.open(fj,'w')
f.write(gem_info)
f.close

cmd = "cd rails3_#{ARGV}  && bundle install vendor --disable-shared-gems"
system(cmd)
