#!/bin/sh
for file in $(find ./log -maxdepth 1 -type f)
do
  cat /dev/null > $file
done

for file in $(find ./tmp -maxdepth 1 -type  f)
do
  rm $file
done

rm -rf coverage
rm -f coverage.data
ruby script/server -p 3010 $1 $2
