#!/usr/bin/env ruby

require_relative 'common.rb'

# Tags the current branch with datetime and pushes the tags.
#
# Usage :
#
# stand in the branch you want to tag and execute
# tagme

execute_cmd %Q{ git tag `git name-rev --name-only HEAD`-`date \"+%Y%m%d%H%M%S\"`  }

execute_cmd %Q{ git push --tags }
