#!/usr/bin/env ruby

# this script 
# - gets the latest master
# - merges master to the current branch 
# - push the branch to github
#
# Usage :
# stand in a branch and execute uptd
#

def update_master

  cmd = 'git checkout master'
  `#{cmd}`

  cmd = 'git pull'
  `#{cmd}`

end

def rebase_current_branch branch_name
  cmd = "git checkout #{branch_name}"
  `#{cmd}`

  cmd = 'git merge master'
  `#{cmd}`

  cmd = 'git push'
  `#{cmd}`

end


current_branch_name = `git symbolic-ref HEAD`.gsub(%r[refs/heads/],'').strip

update_master
rebase_current_branch(current_branch_name) unless current_branch_name == 'master'






